version: "3"

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mysqlpass
            MYSQL_DATABASE: mysqldb
        volumes:
            - ./db:/var/lib/mysql
        ports:
            - 3306:3306

    web:
        # image: spirent-result-portal
        build: .
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - db
